### ISSUE TITLE
NoMethodError: undefined method `retry?' for {"N-<o`e"=>""}:Hash

### ISSUE THREAD

**Issue by mauricioszabo** [rantly-rb/rantly#39]
Using Rantly `1.1.0`, and ruby `2.4.1p111`, I tried a simple test that would fail:

```ruby
require 'rantly/shrinks'
require 'rantly/rspec_extensions'

describe "Test" do
  it "fails" do
     property_of {
       dict { [string, string] }
     }.check { |i|
       expect(i).to be_a(Integer)
     }
  end
end
```

will give me the output:

```

failure: 0 tests, on:
{"?A11+I"=>"\\=>B{A",
 "6xpu|C"=>".\\T7^k",
 "!Jo/Ly"=>"G'j-Q`",
 "WuEo5C"=>"px p-c",
 ".]uXT8"=>"X\"G~NZ",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 0:
{"?A11+I"=>"\\=>B{A",
 "6xpu|C"=>".\\T7^k",
 "!Jo/Ly"=>"G'j-Q`",
 "WuEo5C"=>"px p-c",
 ".]uXT8"=>"X\"G~NZ",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 1:
{"?A11+I"=>"\\=B{A",
 "6xpu|C"=>".\\T7^k",
 "!Jo/Ly"=>"G'j-Q`",
 "WuEo5C"=>"px p-c",
 ".]uXT8"=>"X\"G~NZ",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 2:
{"?A11+I"=>"\\=B{",
 "6xpu|C"=>".\\T7^k",
 "!Jo/Ly"=>"G'j-Q`",
 "WuEo5C"=>"px p-c",
 ".]uXT8"=>"X\"G~NZ",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 3:
{"?A11+I"=>"\\={",
 "6xpu|C"=>".\\T7^k",
 "!Jo/Ly"=>"G'j-Q`",
 "WuEo5C"=>"px p-c",
 ".]uXT8"=>"X\"G~NZ",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 4:
{"?A11+I"=>"\\=",
 "6xpu|C"=>".\\T7^k",
 "!Jo/Ly"=>"G'j-Q`",
 "WuEo5C"=>"px p-c",
 ".]uXT8"=>"X\"G~NZ",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 5:
{"?A11+I"=>"\\",
 "6xpu|C"=>".\\T7^k",
 "!Jo/Ly"=>"G'j-Q`",
 "WuEo5C"=>"px p-c",
 ".]uXT8"=>"X\"G~NZ",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 6:
{"?A11+I"=>"",
 "6xpu|C"=>".\\T7^k",
 "!Jo/Ly"=>"G'j-Q`",
 "WuEo5C"=>"px p-c",
 ".]uXT8"=>"X\"G~NZ",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 7:
{"?A11+I"=>"",
 "6xpu|C"=>"\\T7^k",
 "!Jo/Ly"=>"G'j-Q`",
 "WuEo5C"=>"px p-c",
 ".]uXT8"=>"X\"G~NZ",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 8:
{"?A11+I"=>"",
 "6xpu|C"=>"\\T7k",
 "!Jo/Ly"=>"G'j-Q`",
 "WuEo5C"=>"px p-c",
 ".]uXT8"=>"X\"G~NZ",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 9:
{"?A11+I"=>"",
 "6xpu|C"=>"T7k",
 "!Jo/Ly"=>"G'j-Q`",
 "WuEo5C"=>"px p-c",
 ".]uXT8"=>"X\"G~NZ",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 10:
{"?A11+I"=>"",
 "6xpu|C"=>"Tk",
 "!Jo/Ly"=>"G'j-Q`",
 "WuEo5C"=>"px p-c",
 ".]uXT8"=>"X\"G~NZ",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 11:
{"?A11+I"=>"",
 "6xpu|C"=>"k",
 "!Jo/Ly"=>"G'j-Q`",
 "WuEo5C"=>"px p-c",
 ".]uXT8"=>"X\"G~NZ",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 12:
{"?A11+I"=>"",
 "6xpu|C"=>"",
 "!Jo/Ly"=>"G'j-Q`",
 "WuEo5C"=>"px p-c",
 ".]uXT8"=>"X\"G~NZ",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 13:
{"?A11+I"=>"",
 "6xpu|C"=>"",
 "!Jo/Ly"=>"G'-Q`",
 "WuEo5C"=>"px p-c",
 ".]uXT8"=>"X\"G~NZ",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 14:
{"?A11+I"=>"",
 "6xpu|C"=>"",
 "!Jo/Ly"=>"G'-Q",
 "WuEo5C"=>"px p-c",
 ".]uXT8"=>"X\"G~NZ",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 15:
{"?A11+I"=>"",
 "6xpu|C"=>"",
 "!Jo/Ly"=>"G'Q",
 "WuEo5C"=>"px p-c",
 ".]uXT8"=>"X\"G~NZ",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 16:
{"?A11+I"=>"",
 "6xpu|C"=>"",
 "!Jo/Ly"=>"'Q",
 "WuEo5C"=>"px p-c",
 ".]uXT8"=>"X\"G~NZ",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 17:
{"?A11+I"=>"",
 "6xpu|C"=>"",
 "!Jo/Ly"=>"'",
 "WuEo5C"=>"px p-c",
 ".]uXT8"=>"X\"G~NZ",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 18:
{"?A11+I"=>"",
 "6xpu|C"=>"",
 "!Jo/Ly"=>"",
 "WuEo5C"=>"px p-c",
 ".]uXT8"=>"X\"G~NZ",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 19:
{"?A11+I"=>"",
 "6xpu|C"=>"",
 "!Jo/Ly"=>"",
 "WuEo5C"=>"p p-c",
 ".]uXT8"=>"X\"G~NZ",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 20:
{"?A11+I"=>"",
 "6xpu|C"=>"",
 "!Jo/Ly"=>"",
 "WuEo5C"=>"pp-c",
 ".]uXT8"=>"X\"G~NZ",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 21:
{"?A11+I"=>"",
 "6xpu|C"=>"",
 "!Jo/Ly"=>"",
 "WuEo5C"=>"pp-",
 ".]uXT8"=>"X\"G~NZ",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 22:
{"?A11+I"=>"",
 "6xpu|C"=>"",
 "!Jo/Ly"=>"",
 "WuEo5C"=>"p-",
 ".]uXT8"=>"X\"G~NZ",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 23:
{"?A11+I"=>"",
 "6xpu|C"=>"",
 "!Jo/Ly"=>"",
 "WuEo5C"=>"-",
 ".]uXT8"=>"X\"G~NZ",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 24:
{"?A11+I"=>"",
 "6xpu|C"=>"",
 "!Jo/Ly"=>"",
 "WuEo5C"=>"",
 ".]uXT8"=>"X\"G~NZ",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 25:
{"?A11+I"=>"",
 "6xpu|C"=>"",
 "!Jo/Ly"=>"",
 "WuEo5C"=>"",
 ".]uXT8"=>"X\"GNZ",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 26:
{"?A11+I"=>"",
 "6xpu|C"=>"",
 "!Jo/Ly"=>"",
 "WuEo5C"=>"",
 ".]uXT8"=>"\"GNZ",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 27:
{"?A11+I"=>"",
 "6xpu|C"=>"",
 "!Jo/Ly"=>"",
 "WuEo5C"=>"",
 ".]uXT8"=>"\"GZ",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 28:
{"?A11+I"=>"",
 "6xpu|C"=>"",
 "!Jo/Ly"=>"",
 "WuEo5C"=>"",
 ".]uXT8"=>"\"Z",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 29:
{"?A11+I"=>"",
 "6xpu|C"=>"",
 "!Jo/Ly"=>"",
 "WuEo5C"=>"",
 ".]uXT8"=>"\"",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 30:
{"?A11+I"=>"",
 "6xpu|C"=>"",
 "!Jo/Ly"=>"",
 "WuEo5C"=>"",
 ".]uXT8"=>"",
 "rg\\K$h"=>"|n3!]W"}
Shrinking at depth 31:
{"?A11+I"=>"",
 "6xpu|C"=>"",
 "!Jo/Ly"=>"",
 "WuEo5C"=>"",
 ".]uXT8"=>"",
 "rg\\K$h"=>"n3!]W"}
Shrinking at depth 32:
{"?A11+I"=>"",
 "6xpu|C"=>"",
 "!Jo/Ly"=>"",
 "WuEo5C"=>"",
 ".]uXT8"=>"",
 "rg\\K$h"=>"n!]W"}
Shrinking at depth 33:
{"?A11+I"=>"",
 "6xpu|C"=>"",
 "!Jo/Ly"=>"",
 "WuEo5C"=>"",
 ".]uXT8"=>"",
 "rg\\K$h"=>"n]W"}
Shrinking at depth 34:
{"?A11+I"=>"",
 "6xpu|C"=>"",
 "!Jo/Ly"=>"",
 "WuEo5C"=>"",
 ".]uXT8"=>"",
 "rg\\K$h"=>"nW"}
Shrinking at depth 35:
{"?A11+I"=>"",
 "6xpu|C"=>"",
 "!Jo/Ly"=>"",
 "WuEo5C"=>"",
 ".]uXT8"=>"",
 "rg\\K$h"=>"W"}
Shrinking at depth 36:
{"?A11+I"=>"",
 "6xpu|C"=>"",
 "!Jo/Ly"=>"",
 "WuEo5C"=>"",
 ".]uXT8"=>"",
 "rg\\K$h"=>""}
Shrinking at depth 37:
{"6xpu|C"=>"", "!Jo/Ly"=>"", "WuEo5C"=>"", ".]uXT8"=>"", "rg\\K$h"=>""}
Shrinking at depth 38:
{"!Jo/Ly"=>"", "WuEo5C"=>"", ".]uXT8"=>"", "rg\\K$h"=>""}
Shrinking at depth 39:
{"WuEo5C"=>"", ".]uXT8"=>"", "rg\\K$h"=>""}
Shrinking at depth 40:
{".]uXT8"=>"", "rg\\K$h"=>""}
Shrinking at depth 41:
{"rg\\K$h"=>""}
Shrinking at depth 42:
{}
F

Failures:

  1) Reports that only have new_service events integer property only returns Integer type
     Failure/Error:
       property_of {
         dict { [string, string] }
       }.check { |i|
         expect(i).to be_a(Integer)
       }
     
     NoMethodError:
       undefined method `retry?' for {"rg\\K$h"=>""}:Hash
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:79:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:73:in `rescue in shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:69:in `shrinkify'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:50:in `rescue in check'
     # /home/mauricio/.rvm/gems/ruby-2.4.1/gems/rantly-1.1.0/lib/rantly/property.rb:30:in `check'
     # ./spec/properties/new_service_spec.rb:9:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     #   expected {"?A11+I"=>"\\=>B{A", "6xpu|C"=>".\\T7^k", "!Jo/Ly"=>"G'j-Q`", "WuEo5C"=>"px p-c", ".]uXT8"=>"X\"G~NZ", "rg\\K$h"=>"|n3!]W"} to be a kind of Integer
     #   ./spec/properties/new_service_spec.rb:10:in `block (3 levels) in <top (required)>'

Finished in 0.03759 seconds (files took 0.10705 seconds to load)
1 example, 1 failure
```

**Comment by Ana06** [comment]
Thanks for reporting it @mauricioszabo :bouquet: I am on it! :wink:

**Comment by abargnesi** [comment]
@Ana06 I have added you as an owner using your GitHub email `anamma06@gmail.com`. Great job as current maintainer! :tada:

**Comment by Ana06** [comment]
Thanks @abargnesi! :cupid:

**Comment by Ana06** [comment]
@mauricioszabo new version released! It should work now :wink:
